export const ORDER_SET_CITY_ID = "ORDER_SET_CITY_ID";
export const ORDER_SET_POINT_ID = "ORDER_SET_POINT_ID";
export const SET_ORDER_DATA = "SET_ORDER_DATA";

export const GET_ALL_CARS_DATA = "GET_ALL_CARS_DATA";
export const SET_ALL_CARS_DATA_LOADING = "SET_ALL_CARS_DATA_LOADING";
export const SET_ALL_CARS_DATA = "SET_ALL_CARS_DATA";
export const SET_ALL_CARS_DATA_REQUEST_ERROR = "SET_ALL_CARS_DATA_REQUEST_ERROR";
