export const ORDER_SET_CITY_ID = "ORDER_SET_CITY_ID";
export const ORDER_SET_POINT_ID = "ORDER_SET_POINT_ID";
export const ORDER_SET_CAR_ID = "ORDER_SET_CAR_ID";
export const ORDER_SET_DATE_FROM = "ORDER_SET_DATE_FROM";
export const ORDER_SET_DATE_TO = "ORDER_SET_DATE_TO";
export const ORDER_SET_COLOR = "ORDER_SET_COLOR";
export const ORDER_SET_RATE_ID = "ORDER_SET_RATE_ID";
export const ORDER_SET_PRICE = "ORDER_SET_PRICE";
export const SET_ORDER_DATA_BY_ID = "SET_ORDER_DATA_BY_ID";
export const SET_ADDITIONALLY_BOOLEAN_OPTION = "SET_ADDITIONALLY_BOOLEAN_OPTION";

export const GET_ALL_CARS_DATA = "GET_ALL_CARS_DATA";
export const SET_ALL_CARS_DATA_LOADING = "SET_ALL_CARS_DATA_LOADING";
export const SET_ALL_CARS_DATA = "SET_ALL_CARS_DATA";
export const SET_ALL_CARS_DATA_REQUEST_ERROR = "SET_ALL_CARS_DATA_REQUEST_ERROR";
export const SET_CURRENT_CAR = "SET_CURRENT_CAR";
export const SET_CARS_CATEGORIES_DATA = "SET_CARS_CATEGORIES_DATA";

export const SET_ORDER_STEPS_PASSED = "SET_ORDER_STEPS_PASSED";
export const GET_ORDER_RATES = "GET_ORDER_RATES";
export const SET_ORDER_RATES = "SET_ORDER_RATES";
export const SET_ORDER_RATES_LOADING = "SET_ORDER_RATES_LOADING";
export const SET_ORDER_RATES_ERROR = "SET_ORDER_RATES_ERROR";

export const SEND_ORDER_DATA = "SEND_ORDER_DATA";
export const SEND_ORDER_DATA_LOADING = "SEND_ORDER_DATA_LOADING";
export const SET_ORDER_ID = "SET_ORDER_ID";
export const GET_ORDER_DATA_BY_ID = "GET_ORDER_DATA_BY_ID";
export const GET_ORDER_DATA_LOADING = "GET_ORDER_DATA_LOADING";
export const GET_ORDER_DATA_ERROR = "GET_ORDER_DATA_ERROR";