export const ORDER_SET_CITY_ID = "ORDER_SET_CITY_ID";
export const ORDER_SET_POINT_ID = "ORDER_SET_POINT_ID";
export const ORDER_SET_CAR_ID = "ORDER_SET_CAR_ID";
export const SET_ORDER_DATA = "SET_ORDER_DATA";

export const GET_ALL_CARS_DATA = "GET_ALL_CARS_DATA";
export const SET_ALL_CARS_DATA_LOADING = "SET_ALL_CARS_DATA_LOADING";
export const SET_ALL_CARS_DATA = "SET_ALL_CARS_DATA";
export const SET_ALL_CARS_DATA_REQUEST_ERROR = "SET_ALL_CARS_DATA_REQUEST_ERROR";
export const SET_CURRENT_CAR = "SET_CURRENT_CAR";

export const SET_CARS_CATEGORIES_DATA = "SET_CARS_CATEGORIES_DATA";

export const SET_ORDER_STEPS_PASSED = "SET_ORDER_STEPS_PASSED";

export const GET_ORDER_RATES = "GET_ORDER_RATES";
export const SET_ORDER_RATES = "SET_ORDER_RATES";
export const SET_ORDER_RATES_LOADING = "SET_ORDER_RATES_LOADING";
export const SET_ORDER_RATES_ERROR = "SET_ORDER_RATES_ERROR";