export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_ALL_CITIES = "SET_ALL_CITIES";
export const SET_ALL_CITIES_LOADING = "SET_ALL_CITIES_LOADING";
export const SET_ALL_CITIES_LOADING_ERROR = "SET_ALL_CITIES_LOADING_ERROR";